### ISSUE TITLE
Setting too many attributes at once causing template errors?

### ISSUE THREAD

**Issue by techninja** [hybridsjs/hybrids#124] opened 2020-08-01 23:58 UTC
Hey there, long time fan of this great project! I've already built a few interfaces with it including [my own cv](https://cv.tn42.com), and currently the experimental default interface for my [Robot Drawing API](https://github.com/techninja/cncserver/tree/v3).

I'm currently building out a component for displaying a drawing implement with a number of different attributes that describe it. I initially tried building this out in canvas as it allows me to draw a brush curve with gradient strokes with a lot more control than CSS was allowing me, but I soon found that a litany of host attributes going into a generic render and a single `<canvas>` wasn't going to play nice with Hybrids caching. I hit the books and found that Hybrids supports SVG rendering, so I set about implementing it.

After about a day of work I got it to easily render the intended display.
![image](https://user-images.githubusercontent.com/320747/89112289-79239c00-d415-11ea-8d17-e16efecdf15a.png)

But as soon as I worked to hook this up to being controlled with slider inputs, it broke and I started getting SVG attribute warnings in the console.

![image](https://user-images.githubusercontent.com/320747/89112336-30b8ae00-d416-11ea-998c-cb6a40b62ab7.png)

With the SVG very clearly holding what looks like a template placeholder 🤔

![image](https://user-images.githubusercontent.com/320747/89112349-5b0a6b80-d416-11ea-864a-380b7c9b8645.png)

It does not happen every time, but it's not hard to make up happen. I set all the applicable attributes at the same time on the form data change, and perhaps this is part of the issue?

![image](https://user-images.githubusercontent.com/320747/89112372-a02e9d80-d416-11ea-8319-c6a9b86c63bd.png)

[Code for this is here](https://github.com/techninja/cncserver/blob/8b28ef7145308b4b2798c31b039f11043b289a59/src/interface/modules/components/elements/tool-implement.mjs) and luckily has basically zero other dependencies.

Could this be because we're setting too many attributes too fast? I'm curious to see what you think might be happening. Thanks in advance and I'd be happy to attempt to make a simpler example to root this bug out.

**Comment by techninja** [comment] 2020-08-02 00:08
Just discovered in a little more debugging, my method of constructing attribute strings directly within the template seems to at least partially to blame. The path I was building for the bottom bracket wasn't updating at all during attribute updates, so by building this string in the render function and the attaching it directly to the SVG path `d` attribute was enough to get it to update.

![image](https://user-images.githubusercontent.com/320747/89112564-66ab6180-d419-11ea-92ed-191afff5f361.png)

I'm going to move everything into render function generated strings attached directly to attributes and I suspect will fix the issue for me.

**Comment by techninja** [comment] 2020-08-02 00:35
Looks like I was right and moving everything that was building a string into an attribute out of the main template was enough to get it to behave and correctly display the computed data. I have not removed **_every_** example of data manipulation directly inside of templated attributes seeing as I figured it should work fine? Even though I can move forward here I suspect there's a subtle bug that this points to that is still worth pursuing.

**Comment by smalluban** [comment] 2020-08-03 07:10
> Just discovered in a little more debugging, my method of constructing attribute strings directly within the template seems to at least partially to blame. The path I was building for the bottom bracket wasn't updating at all during attribute updates, so by building this string in the render function and attaching it directly to the SVG path d attribute was enough to get it to update.

Good to hear to find the root cause of the problem. I will try to create a test case where the template expression fails. To be honest, the usage of the template engine in SVG namespace is rather rare, so I think you might be the first person who discovered the bug ;)

**Comment by smalluban** [comment] 2020-09-14 09:10
I tried to reproduce this error in the testing environment but without luck. Everything seems to work properly. I even used your template with all of the parameters ;)  I am not sure what to do next, so for now I am closing the issue. Maybe in the future other people will have a similar issue with different input easier to reproduce.

**Closed by smalluban** 2020-09-14 09:10 UTC
Labels: bug, template engine
