### ISSUE TITLE
'Try to assert value of the '<property_name>' inside of the value function' error while passing children their properties

### ISSUE THREAD

**Issue by gorkat** [hybridsjs/hybrids#273] opened 2024-09-12 13:03 UTC
Hello!

We've been using Hybrids for a while now (and we love it), and it appears that in the latest versions (starting from 9.1.2), passing properties to hybrids children custom elements inside another hybrids custom element's render function makes the component crash with a `Try to assert value of the '<property_name>' inside of the value function` error.

After a bit of research, the error we get seems related to [fix(cache): throw an error when assert while getting the value](https://github.com/hybridsjs/hybrids/commit/9cc25c0b9facdcdf961504f7c1a3267a9017d96a).

In some of our components, we have hybrids custom elements inside some other hybrids custom elements:

``` TS
export const renderLinkPopover = (
    host: InternalLinkPopoverElement,
    gettext_provider: GetText,
): UpdateFunction<InternalLinkPopoverElement> =>
    html`
        <section data-role="popover" class="tlp-popover">
            <div class="tlp-popover-arrow"></div>
            <div class="tlp-popover-body">
                <div class="tlp-button-bar">
                    <open-link-button
                        gettext_provider="${gettext_provider}">
                        sanitized_link_href="${host.sanitized_link_href}"
                    </open-link-button>
                    <copy-to-clipboard-button
                        gettext_provider="${gettext_provider}"
                        value_to_copy="${host.sanitized_link_href}"
                    ></copy-to-clipboard-button>
                </div>
        </section>
    `.style(popover_styles);
```

This render function works fine with hybrids@9.0.0.

This error prevents us to upgrade to the latest version (9.1.5 at the time of writing).

We couldn't find any documentation about it, and there is not that much of context around the patch mentioned above.

What is the right way to pass children custom elements their properties ? What are we doing wrong?

Best regards!

**Comment by smalluban** [comment] 2024-09-12 14:00
Hi. Thanks for raising this up. However, I cannot reproduce the problem. Here you have a test, which shows that everything works as expected: https://github.com/hybridsjs/hybrids/pull/274

The template engine returns an update function, which is called makes assertions, but the function is not called when the `render` evaluates. It's called in the observe callback, outside of that context. 

If you have that error, it means, that you must directly set a property value inside of that get call of `render` or other property of the root elements.

Can you provide a call stack of that error?  Or simplify the example, still keeping the error. I think it might be helpful, to show where exactly the assertion is done.

**Comment by smalluban** [comment] 2024-09-13 19:27
Thanks for the details. I know how to fix it, still not removing the constraint completely, but I would like to understand why it happens first. 

I'll look at this on Monday or later. Until I fix it, please keep the latest version without the bug.

**Comment by smalluban** [comment] 2024-09-20 08:21
After a while, I found a case, where the `render()` must be called manually in another property - then the update process is made inside of the get call of that property. The fix is merged. I'll release a new version in a few minutes.

**Closed by smalluban** 2024-09-20 08:21 UTC
Labels: bug, render, properties
